import type { Ship } from './types'

export const SHIPS: Ship[] = [
  // ─── Rate VII ────────────────────────────────────────────────────────────────
  { id: 'pickle', name: 'Pickle', shipType: 'Fast', rate: 7, slots: 6, durability: 700, speed: 9.2, maneuverability: 94, broadsideArmor: 1.6, hold: 6000, crew: 66, hullDims: '24x4', displacement: '900t', heavyWeapons: '0-6-0', swivelGuns: 4, integrity: null, info: 'Fast-moving Schooner VII rate.' },
  { id: 'horizont', name: 'Horizont', shipType: 'Balanced', rate: 7, slots: 8, durability: 850, speed: 8.4, maneuverability: 80, broadsideArmor: 3.2, hold: 7000, crew: 78, hullDims: '26x5', displacement: '1125t', heavyWeapons: '2-8-0', swivelGuns: 6, integrity: null, info: 'Battle Brigantine VII rate.' },
  { id: 'friede', name: 'Friede', shipType: 'Support', rate: 7, slots: 7, durability: 750, speed: 8.8, maneuverability: 86, broadsideArmor: 2.2, hold: 11000, crew: 72, hullDims: '33x6', displacement: '1350t', heavyWeapons: '2-7-0', swivelGuns: 6, integrity: null, info: 'Transport Flute VII rate.' },

  // ─── Rate VI ────────────────────────────────────────────────────────────────
  { id: 'le_cerf', name: 'Le Cerf', shipType: 'Fast', rate: 6, slots: 9, durability: 900, speed: 10, maneuverability: 97, broadsideArmor: 1.8, hold: 8000, crew: 78, hullDims: '22x3', displacement: '990t', heavyWeapons: '0-9-0', swivelGuns: 8, integrity: 6, info: 'Fast-moving Cutter VI rate.' },
  { id: 'la_salamandre', name: 'La Salamandre', shipType: 'Balanced', rate: 6, slots: 10, durability: 1160, speed: 8.8, maneuverability: 82, broadsideArmor: 3.6, hold: 9500, crew: 96, hullDims: '25x5', displacement: '1350t', heavyWeapons: '2-10-0', swivelGuns: 6, integrity: null, info: 'Battle Ketch VI rate.' },
  { id: 'balloon', name: 'Balloon', shipType: 'Special', rate: 6, slots: 0, durability: 200, speed: 21, maneuverability: 50, broadsideArmor: 1, hold: 1000, crew: 8, hullDims: '—', displacement: '—', heavyWeapons: '—', swivelGuns: 0, integrity: null, info: 'Imperial Montgolfiere VI rate.' },
  { id: 'mercury', name: 'Mercury', shipType: 'Support', rate: 6, slots: 9, durability: 1040, speed: 9.2, maneuverability: 89, broadsideArmor: 2.5, hold: 15500, crew: 88, hullDims: '32x8', displacement: '2025t', heavyWeapons: '2-9-0', swivelGuns: 6, integrity: null, info: 'Transport Galleon VI rate.' },
  { id: 'phoenix', name: 'Phoenix', shipType: 'Heavy', rate: 6, slots: 12, durability: 1380, speed: 8.2, maneuverability: 75, broadsideArmor: 4.5, hold: 12500, crew: 104, hullDims: '27x6', displacement: '1440t', heavyWeapons: '0-12-0', swivelGuns: 6, integrity: null, info: 'Heavy Brig VI rate.' },
  { id: 'savannah', name: 'Savannah', shipType: 'Fast', rate: 6, slots: 9, durability: 1000, speed: 10.8, maneuverability: 92, broadsideArmor: 3, hold: 10000, crew: 94, hullDims: '39x4', displacement: '1575t', heavyWeapons: '0-9-0', swivelGuns: 6, integrity: null, info: 'Fast-moving Frigate VI rate (steam-powered).' },
  { id: 'shunsen', name: 'Shunsen', shipType: 'Balanced', rate: 6, slots: 10, durability: 1000, speed: 8.5, maneuverability: 90, broadsideArmor: 3, hold: 11000, crew: 92, hullDims: '28x6', displacement: '1485t', heavyWeapons: '0-10-0', swivelGuns: 8, integrity: null, info: 'Battle Junk VI rate.' },
  { id: 'polacca', name: 'Polacca', shipType: 'Special', rate: 6, slots: 7, durability: 980, speed: 9, maneuverability: 102, broadsideArmor: 2.9, hold: 9000, crew: 74, hullDims: '23x5', displacement: '1575t', heavyWeapons: '0-7-0', swivelGuns: 6, integrity: 5, info: 'Siege Polacca VI rate. Carries 1 mortar caliber 6 in.' },
  { id: 'golden_apostle', name: 'Golden Apostle', shipType: 'Special', rate: 6, slots: 7, durability: 900, speed: 9.5, maneuverability: 120, broadsideArmor: 2.2, hold: 8500, crew: 96, hullDims: '23x3', displacement: '1260t', heavyWeapons: '0-7-0', swivelGuns: 6, integrity: 5, info: 'Siege Cutter VI rate. Carries 1 mortar caliber 6 in.' },

  // ─── Rate V ─────────────────────────────────────────────────────────────────
  { id: 'black_prince', name: 'Black Prince', shipType: 'Special', rate: 5, slots: 15, durability: 1700, speed: 9.9, maneuverability: 90, broadsideArmor: 3, hold: 14500, crew: 120, hullDims: '37x7', displacement: '1800t', heavyWeapons: '2-15-2', swivelGuns: 6, integrity: 6, info: 'Imperial Galleon V rate.' },
  { id: 'la_creole', name: 'La Creole', shipType: 'Fast', rate: 5, slots: 12, durability: 1400, speed: 11, maneuverability: 100, broadsideArmor: 2, hold: 11000, crew: 96, hullDims: '39x5', displacement: '1620t', heavyWeapons: '4-12-0', swivelGuns: 8, integrity: 7, info: 'Fast-moving Corvette V rate.' },
  { id: 'san_martin', name: 'San Martin', shipType: 'Heavy', rate: 5, slots: 20, durability: 2140, speed: 8.5, maneuverability: 72, broadsideArmor: 5, hold: 17500, crew: 126, hullDims: '40x9', displacement: '2475t', heavyWeapons: '0-20-0', swivelGuns: 6, integrity: 7, info: 'Heavy Galleon V rate. Flagship of the Spanish Armada.' },
  { id: 'black_wind', name: 'Black Wind', shipType: 'Balanced', rate: 5, slots: 16, durability: 1820, speed: 9.4, maneuverability: 84, broadsideArmor: 4, hold: 13000, crew: 116, hullDims: '45x8', displacement: '2250t', heavyWeapons: '2-16-2', swivelGuns: 6, integrity: 6, info: 'Battle Frigate V rate.' },
  { id: 'russia', name: 'Russia', shipType: 'Support', rate: 5, slots: 14, durability: 1600, speed: 9.9, maneuverability: 91, broadsideArmor: 2.7, hold: 22000, crew: 108, hullDims: '37x7', displacement: '2070t', heavyWeapons: '2-14-0', swivelGuns: 6, integrity: 7, info: 'Transport Frigate V rate.' },
  { id: 'kwee_song', name: 'Kwee Song', shipType: 'Balanced', rate: 5, slots: 10, durability: 1360, speed: 7.9, maneuverability: 105, broadsideArmor: 4.5, hold: 12500, crew: 108, hullDims: '22x7', displacement: '1800t', heavyWeapons: '0-10-10', swivelGuns: 6, integrity: 6, info: 'Battle Phanokson V rate.' },
  { id: 'southampton', name: 'Southampton', shipType: 'Support', rate: 5, slots: 15, durability: 1760, speed: 9.7, maneuverability: 88, broadsideArmor: 3.2, hold: 20500, crew: 102, hullDims: '46x8', displacement: '1980t', heavyWeapons: '2-15-0', swivelGuns: 10, integrity: 7, info: 'Transport Frigate V rate.' },
  { id: 'axel_thorsen', name: 'Axel Thorsen', shipType: 'Special', rate: 5, slots: 0, durability: 880, speed: 9.8, maneuverability: 110, broadsideArmor: 5, hold: 7500, crew: 66, hullDims: '22x3', displacement: '900t', heavyWeapons: '0-0-0', swivelGuns: 10, integrity: 7, info: 'Fast-moving Schooner V rate. Carries 1 Imperial Bombard.' },
  { id: 'le_requin', name: 'Le Requin', shipType: 'Special', rate: 5, slots: 12, durability: 1520, speed: 9.6, maneuverability: 105, broadsideArmor: 3.2, hold: 12500, crew: 88, hullDims: '37x4', displacement: '2025t', heavyWeapons: '2-12-0', swivelGuns: 6, integrity: 6, info: 'Siege Xebec V rate. Carries 1 mortar caliber 7 in.' },
  { id: 'eagle', name: 'Eagle', shipType: 'Special', rate: 5, slots: 8, durability: 1600, speed: 9.4, maneuverability: 110, broadsideArmor: 2.2, hold: 14000, crew: 84, hullDims: '27x6', displacement: '1575t', heavyWeapons: '4-8-0', swivelGuns: 6, integrity: 8, info: 'Siege Flute V rate. Carries 2 mortars caliber 7 in.' },

  // ─── Rate IV ─────────────────────────────────────────────────────────────────
  { id: 'surprise', name: 'Surprise', shipType: 'Fast', rate: 4, slots: 18, durability: 1680, speed: 10.5, maneuverability: 105, broadsideArmor: 2.4, hold: 13000, crew: 112, hullDims: '45x5', displacement: '2025t', heavyWeapons: '0-18-2', swivelGuns: 8, integrity: 7, info: 'Fast-moving Corvette IV rate.' },
  { id: 'devourer', name: 'Devourer', shipType: 'Special', rate: 4, slots: 12, durability: 1760, speed: 7.5, maneuverability: 110, broadsideArmor: 5.5, hold: 17000, crew: 144, hullDims: '37x7', displacement: '2610t', heavyWeapons: '12-11-8', swivelGuns: 8, integrity: 6, info: 'Imperial Barque IV rate.' },
  { id: 'essex', name: 'Essex', shipType: 'Balanced', rate: 4, slots: 21, durability: 2160, speed: 8.9, maneuverability: 88, broadsideArmor: 4.8, hold: 15500, crew: 136, hullDims: '38x6', displacement: '2115t', heavyWeapons: '2-21-2', swivelGuns: 8, integrity: 6, info: 'Battle Frigate IV rate.' },
  { id: 'falmouth', name: 'Falmouth', shipType: 'Support', rate: 4, slots: 18, durability: 1920, speed: 9.4, maneuverability: 96, broadsideArmor: 3.3, hold: 27500, crew: 126, hullDims: '44x8', displacement: '3060t', heavyWeapons: '4-18-0', swivelGuns: 8, integrity: 7, info: 'Transport Ship IV rate.' },
  { id: 'constitution', name: 'Constitution', shipType: 'Heavy', rate: 4, slots: 26, durability: 2560, speed: 8, maneuverability: 68, broadsideArmor: 6, hold: 21500, crew: 148, hullDims: '53x6', displacement: '2565t', heavyWeapons: '0-26-0', swivelGuns: 8, integrity: 7, info: 'Heavy Frigate IV rate. "Old Ironsides".' },
  { id: 'friedrich_wilhelm', name: 'Friedrich Wilhelm', shipType: 'Support', rate: 4, slots: 21, durability: 2020, speed: 9.4, maneuverability: 96, broadsideArmor: 3.5, hold: 26000, crew: 120, hullDims: '45x11', displacement: '2700t', heavyWeapons: '4-21-4', swivelGuns: 8, integrity: 7, info: 'Transport Frigate IV rate.' },
  { id: 'three_hierarchs', name: 'Three Hierarchs', shipType: 'Heavy', rate: 4, slots: 27, durability: 2420, speed: 8.4, maneuverability: 72, broadsideArmor: 5.6, hold: 21000, crew: 152, hullDims: '48x9', displacement: '2475t', heavyWeapons: '0-27-0', swivelGuns: 10, integrity: 7, info: 'Heavy Ship of the Line IV rate.' },
  { id: 'flying_cloud', name: 'Flying Cloud', shipType: 'Support', rate: 4, slots: 16, durability: 1800, speed: 11.5, maneuverability: 58, broadsideArmor: 2.9, hold: 30000, crew: 100, hullDims: '60x8', displacement: '3375t', heavyWeapons: '0-16-0', swivelGuns: 10, integrity: 7, info: 'Transport Clipper IV rate. Fastest voyage record holder.' },
  { id: 'red_arrow', name: 'Red Arrow', shipType: 'Balanced', rate: 4, slots: 15, durability: 1940, speed: 8.6, maneuverability: 95, broadsideArmor: 5.5, hold: 18000, crew: 140, hullDims: '38x6', displacement: '2700t', heavyWeapons: '0-15-6', swivelGuns: 8, integrity: 8, info: 'Battle Galleon IV rate. Carries 1 mortar caliber 7 in.' },
  { id: 'sparrow', name: 'Sparrow', shipType: 'Special', rate: 4, slots: 4, durability: 1000, speed: 9.1, maneuverability: 95, broadsideArmor: 1.5, hold: 10000, crew: 72, hullDims: '25x4', displacement: '1350t', heavyWeapons: '0-4-0', swivelGuns: 8, integrity: 8, info: 'Siege Tartane IV rate. Carries 3 mortars caliber 8 in.' },

  // ─── Rate III ────────────────────────────────────────────────────────────────
  { id: 'poltava', name: 'Poltava', shipType: 'Fast', rate: 3, slots: 23, durability: 2100, speed: 9.6, maneuverability: 95, broadsideArmor: 2.8, hold: 15500, crew: 132, hullDims: '41x6', displacement: '2475t', heavyWeapons: '0-23-4', swivelGuns: 10, integrity: 7, info: 'Fast-moving Ship of the Line III rate.' },
  { id: 'anson', name: 'Anson', shipType: 'Balanced', rate: 3, slots: 30, durability: 2700, speed: 8.2, maneuverability: 80, broadsideArmor: 5.6, hold: 18500, crew: 160, hullDims: '52x10', displacement: '3150t', heavyWeapons: '4-30-2', swivelGuns: 8, integrity: 6, info: 'Battle Ship of the Line III rate.' },
  { id: 'deadfish', name: 'Deadfish', shipType: 'Special', rate: 3, slots: 25, durability: 3000, speed: 6.6, maneuverability: 66, broadsideArmor: 8, hold: 27000, crew: 166, hullDims: '47x11', displacement: '4950t', heavyWeapons: '8-25-1', swivelGuns: 10, integrity: 7, info: 'Imperial Ship III rate.' },
  { id: 'mordaunt', name: 'Mordaunt', shipType: 'Support', rate: 3, slots: 26, durability: 2380, speed: 8.7, maneuverability: 87, broadsideArmor: 3.9, hold: 34000, crew: 148, hullDims: '41x7', displacement: '2475t', heavyWeapons: '4-26-0', swivelGuns: 6, integrity: 7, info: 'Transport Ship of the Line III rate.' },
  { id: 'bellona', name: 'Bellona', shipType: 'Heavy', rate: 3, slots: 35, durability: 3180, speed: 7.5, maneuverability: 62, broadsideArmor: 7, hold: 26000, crew: 174, hullDims: '49x9', displacement: '3915t', heavyWeapons: '0-35-0', swivelGuns: 10, integrity: 7, info: 'Heavy Ship of the Line III rate.' },
  { id: 'kobukson', name: 'Kobukson', shipType: 'Special', rate: 3, slots: 15, durability: 2000, speed: 8, maneuverability: 85, broadsideArmor: 4.6, hold: 18000, crew: 124, hullDims: '37x6', displacement: '2250t', heavyWeapons: '0-15-0', swivelGuns: 8, integrity: 6, info: 'Siege Phanokson III rate. Carries up to 4 mortars caliber 9 in.' },
  { id: 'azov', name: 'Azov', shipType: 'Heavy', rate: 3, slots: 35, durability: 3000, speed: 7.7, maneuverability: 65, broadsideArmor: 6.7, hold: 26000, crew: 174, hullDims: '53x10', displacement: '3150t', heavyWeapons: '8-35-6', swivelGuns: 8, integrity: 7, info: 'Heavy Ship of the Line III rate. Hero of the Battle of Navarino.' },
  { id: 'iberia', name: 'Iberia', shipType: 'Fast', rate: 3, slots: 24, durability: 2220, speed: 9.3, maneuverability: 92, broadsideArmor: 3.1, hold: 16500, crew: 140, hullDims: '54x8', displacement: '2565t', heavyWeapons: '0-24-4', swivelGuns: 10, integrity: 7, info: 'Fast-moving Frigate III rate.' },
  { id: 'le_saint_louis', name: 'Le Saint Louis', shipType: 'Balanced', rate: 3, slots: 26, durability: 2700, speed: 7.9, maneuverability: 78, broadsideArmor: 5.6, hold: 20000, crew: 170, hullDims: '52x13', displacement: '2925t', heavyWeapons: '6-26-6', swivelGuns: 10, integrity: 6, info: 'Battle Ship of the Line III rate.' },
  { id: 'shen', name: 'Shen', shipType: 'Special', rate: 3, slots: 22, durability: 2160, speed: 7.9, maneuverability: 85, broadsideArmor: 5.2, hold: 19000, crew: 158, hullDims: '52x7', displacement: '2925t', heavyWeapons: '0-22-1', swivelGuns: 8, integrity: 6, info: 'Siege Galiot III rate. Carries 2 mortars 11 in. and 1 special weapon.' },
  { id: 'prins_willem', name: 'Prins Willem', shipType: 'Support', rate: 3, slots: 26, durability: 2440, speed: 8.5, maneuverability: 78, broadsideArmor: 4.8, hold: 45000, crew: 170, hullDims: '53x11', displacement: '3150t', heavyWeapons: '6-26-4', swivelGuns: 8, integrity: 8, info: 'Transport Galleon III rate. +1 upgrade spaces.' },

  // ─── Rate II ─────────────────────────────────────────────────────────────────
  { id: 'octopus', name: 'Octopus', shipType: 'Special', rate: 2, slots: 37, durability: 2760, speed: 8.3, maneuverability: 75, broadsideArmor: 6.8, hold: 23000, crew: 176, hullDims: '48x7', displacement: '3375t', heavyWeapons: '8-37-0', swivelGuns: 10, integrity: 4, info: 'Imperial Ship II rate.' },
  { id: 'ingermanland', name: 'Ingermanland', shipType: 'Fast', rate: 2, slots: 32, durability: 2340, speed: 9, maneuverability: 87, broadsideArmor: 3.2, hold: 17500, crew: 152, hullDims: '48x8', displacement: '3060t', heavyWeapons: '0-32-4', swivelGuns: 12, integrity: 7, info: 'Fast-moving Ship of the Line II rate.' },
  { id: 'sans_pareil', name: 'Sans Pareil', shipType: 'Balanced', rate: 2, slots: 38, durability: 3000, speed: 7.7, maneuverability: 74, broadsideArmor: 6.4, hold: 21500, crew: 184, hullDims: '55x6', displacement: '3330t', heavyWeapons: '4-38-2', swivelGuns: 10, integrity: 6, info: 'Battle Ship of the Line II rate.' },
  { id: 'la_sirene', name: 'La Sirene', shipType: 'Support', rate: 2, slots: 32, durability: 2660, speed: 8.1, maneuverability: 80, broadsideArmor: 4.4, hold: 43000, crew: 170, hullDims: '50x9', displacement: '3600t', heavyWeapons: '4-32-0', swivelGuns: 8, integrity: 7, info: 'Transport Ship II rate.' },
  { id: 'redoutable', name: 'Redoutable', shipType: 'Heavy', rate: 2, slots: 43, durability: 3540, speed: 7, maneuverability: 57, broadsideArmor: 8, hold: 30500, crew: 198, hullDims: '53x7', displacement: '3600t', heavyWeapons: '0-43-0', swivelGuns: 10, integrity: 7, info: 'Heavy Ship of the Line II rate. Fired the shot that killed Nelson.' },
  { id: 'vasa', name: 'Vasa', shipType: 'Heavy', rate: 2, slots: 31, durability: 4040, speed: 6.6, maneuverability: 64, broadsideArmor: 7.5, hold: 35000, crew: 206, hullDims: '47x11', displacement: '3825t', heavyWeapons: '4-31-2', swivelGuns: 14, integrity: 7, info: 'Heavy Ship of the Line II rate.' },
  { id: 'firestorm', name: 'Firestorm', shipType: 'Fast', rate: 2, slots: 28, durability: 2600, speed: 8.7, maneuverability: 85, broadsideArmor: 4.2, hold: 20000, crew: 170, hullDims: '46x8', displacement: '3150t', heavyWeapons: '12-28-1', swivelGuns: 10, integrity: 8, info: 'Fast-moving Frigate II rate. Has 1 special weapon.' },
  { id: 'adventure', name: 'Adventure', shipType: 'Special', rate: 2, slots: 19, durability: 2660, speed: 8.2, maneuverability: 92, broadsideArmor: 5.2, hold: 21000, crew: 140, hullDims: '47x6', displacement: '2925t', heavyWeapons: '4-19-0', swivelGuns: 8, integrity: 6, info: 'Siege Galley II rate. Carries up to 2 mortars caliber 10 in.' },
  { id: 'montanes', name: 'Montanes', shipType: 'Balanced', rate: 2, slots: 38, durability: 2940, speed: 7.5, maneuverability: 71, broadsideArmor: 7.2, hold: 23500, crew: 194, hullDims: '59x11', displacement: '3420t', heavyWeapons: '6-38-4', swivelGuns: 10, integrity: 6, info: 'Battle Ship of the Line II rate.' },
  { id: 'neptuno', name: 'Neptuno', shipType: 'Balanced', rate: 2, slots: 36, durability: 2900, speed: 8.2, maneuverability: 80, broadsideArmor: 5.8, hold: 28000, crew: 194, hullDims: '46x9', displacement: '4050t', heavyWeapons: '4-36-4', swivelGuns: 10, integrity: 8, info: 'Battle Galleon II rate.' },
  { id: 'st_pavel', name: 'St. Pavel', shipType: 'Heavy', rate: 2, slots: 44, durability: 3260, speed: 7.3, maneuverability: 64, broadsideArmor: 7.3, hold: 33500, crew: 190, hullDims: '47x8', displacement: '4050t', heavyWeapons: '2-44-0', swivelGuns: 10, integrity: 7, info: 'Heavy Ship of the Line II rate.' },

  // ─── Rate I ──────────────────────────────────────────────────────────────────
  { id: 'huracan', name: 'Huracan', shipType: 'Special', rate: 1, slots: 85, durability: 8000, speed: 5.5, maneuverability: 42, broadsideArmor: 11.5, hold: 54000, crew: 288, hullDims: '90x18', displacement: '5625t', heavyWeapons: '0-85-2', swivelGuns: 18, integrity: 7, info: 'Imperial Ship of the Line I rate.' },
  { id: 'victory', name: 'Victory', shipType: 'Balanced', rate: 1, slots: 49, durability: 3740, speed: 7.1, maneuverability: 66, broadsideArmor: 8, hold: 25000, crew: 204, hullDims: '61x12', displacement: '4050t', heavyWeapons: '4-49-4', swivelGuns: 10, integrity: 6, info: 'Battle Ship of the Line I rate. Nelson\'s flagship at Trafalgar.' },
  { id: 'la_couronne', name: 'La Couronne', shipType: 'Support', rate: 1, slots: 28, durability: 3500, speed: 7.6, maneuverability: 72, broadsideArmor: 5.5, hold: 50000, crew: 188, hullDims: '61x9', displacement: '4500t', heavyWeapons: '8-28-0', swivelGuns: 14, integrity: 7, info: 'Transport Galleon I rate.' },
  { id: 'apostolov_12', name: '12 Apostolov', shipType: 'Heavy', rate: 1, slots: 59, durability: 4400, speed: 6.2, maneuverability: 49, broadsideArmor: 10, hold: 36000, crew: 220, hullDims: '66x11', displacement: '4500t', heavyWeapons: '0-59-0', swivelGuns: 10, integrity: 7, info: 'Heavy Ship of the Line I rate. Scuttled to block Sevastopol harbor.' },
  { id: 'la_royale', name: 'La Royale', shipType: 'Special', rate: 1, slots: 18, durability: 2900, speed: 7.4, maneuverability: 83, broadsideArmor: 6.5, hold: 24000, crew: 156, hullDims: '60x9', displacement: '3870t', heavyWeapons: '0-18-6', swivelGuns: 12, integrity: 6, info: 'Siege Galley I rate. Carries up to 3 mortars caliber 11 in.' },
  { id: 'sovereign', name: 'Sovereign', shipType: 'Balanced', rate: 1, slots: 38, durability: 3600, speed: 7.4, maneuverability: 70, broadsideArmor: 7, hold: 26500, crew: 192, hullDims: '48x11', displacement: '4275t', heavyWeapons: '4-38-8', swivelGuns: 10, integrity: 6, info: 'Battle Galleon I rate. Carries up to 2 mortars caliber 7 in.' },
  { id: 'santisima_trinidad', name: 'Santisima Trinidad', shipType: 'Heavy', rate: 1, slots: 63, durability: 4160, speed: 6.4, maneuverability: 54, broadsideArmor: 9, hold: 39500, crew: 212, hullDims: '61x10', displacement: '4500t', heavyWeapons: '4-63-0', swivelGuns: 10, integrity: 8, info: 'Heavy Ship of the Line I rate. Fought at Trafalgar. +15% XP and loot.' },
  { id: 'de_zeven_provincien', name: 'De Zeven Provincien', shipType: 'Balanced', rate: 1, slots: 42, durability: 3320, speed: 7.7, maneuverability: 75, broadsideArmor: 8.6, hold: 26000, crew: 188, hullDims: '51x8', displacement: '4140t', heavyWeapons: '4-42-4', swivelGuns: 10, integrity: 8, info: 'Battle Ship of the Line I rate. Flagship of Admiral de Ruyter.' },
]

// ─── Helpers ─────────────────────────────────────────────────────────────────

export function getShipById(id: string): Ship | undefined {
  return SHIPS.find((s) => s.id === id)
}

export function parseWeaponSlots(heavyWeapons: string): {
  bow: number
  broadside: number
  stern: number
} {
  if (!heavyWeapons || heavyWeapons === '—') return { bow: 0, broadside: 0, stern: 0 }
  const parts = heavyWeapons.split('-').map(Number)
  return {
    bow: parts[0] ?? 0,
    broadside: parts[1] ?? 0,
    stern: parts[2] ?? 0,
  }
}

export const SHIP_RATES = [1, 2, 3, 4, 5, 6, 7] as const
export const SHIP_TYPES = ['Fast', 'Balanced', 'Heavy', 'Support', 'Special'] as const
