import type { Cannon } from './types'

export const CANNONS: Cannon[] = [
  // ─── Empty placeholder ──────────────────────────────────────────────────────
  {
    id: 'none',
    category: 'None',
    rank: '',
    dmg: 0,
    penetration: 0,
    shots: 1,
    reloadTime: 0,
    range: 0,
    maxAngle: 0,
    scatter: 0,
    name: '— Empty —',
    desc: '',
  },

  // ─── Cannons ────────────────────────────────────────────────────────────────
  {
    id: 'cannon_rusty_6pdr',
    category: 'Cannon',
    rank: 'VII–VI',
    dmg: 13,
    penetration: 13,
    shots: 1,
    reloadTime: 10.5,
    range: 125,
    maxAngle: 34,
    scatter: 8.5,
    name: '6-pdr Rusty Cannon',
    desc: 'Fast-firing starter cannon.',
  },
  {
    id: 'cannon_8pdr',
    category: 'Cannon',
    rank: 'V–IV',
    dmg: 14,
    penetration: 14,
    shots: 1,
    reloadTime: 9,
    range: 130,
    maxAngle: 31,
    scatter: 9.5,
    name: '8-pdr Cannon',
    desc: 'Standard mid-tier cannon.',
  },
  {
    id: 'cannon_16pdr',
    category: 'Cannon',
    rank: 'IV–III',
    dmg: 14,
    penetration: 14,
    shots: 1,
    reloadTime: 12,
    range: 130,
    maxAngle: 29,
    scatter: 10.5,
    name: '16-pdr Cannon',
    desc: 'Standard medium cannon.',
  },
  {
    id: 'cannon_18pdr',
    category: 'Cannon',
    rank: 'III–II',
    dmg: 15,
    penetration: 15,
    shots: 1,
    reloadTime: 10.5,
    range: 135,
    maxAngle: 26,
    scatter: 12,
    name: '18-pdr Cannon',
    desc: 'Standard heavy medium cannon.',
  },
  {
    id: 'cannon_admiral_20pdr',
    category: 'Cannon',
    rank: 'III–II',
    dmg: 17,
    penetration: 17,
    shots: 1,
    reloadTime: 13.5,
    range: 130,
    maxAngle: 21,
    scatter: 11,
    name: '20-pdr Admiral',
    desc: 'Elite medium cannon with improved penetration.',
  },
  {
    id: 'cannon_inrog_36pdr',
    category: 'Cannon',
    rank: 'II–I',
    dmg: 20,
    penetration: 20,
    shots: 1,
    reloadTime: 16,
    range: 135,
    maxAngle: 16,
    scatter: 13.5,
    name: '36-pdr Inrog',
    desc: 'Heavy cannon with strong penetration.',
  },
  {
    id: 'cannon_32pdr',
    category: 'Cannon',
    rank: 'I',
    dmg: 17.5,
    penetration: 17.5,
    shots: 1,
    reloadTime: 12,
    range: 140,
    maxAngle: 20,
    scatter: 15,
    name: '32-pdr Cannon',
    desc: 'Heavy cannon.',
  },

  // ─── Long Cannons ───────────────────────────────────────────────────────────
  {
    id: 'longcannon_culverin_6pdr',
    category: 'Long Cannon',
    rank: 'VII–VI',
    dmg: 14,
    penetration: 14,
    shots: 1,
    reloadTime: 15.5,
    range: 135,
    maxAngle: 17,
    scatter: 5,
    name: '6-pdr Culverin',
    desc: 'Long-range light culverin.',
  },
  {
    id: 'longcannon_culverin_8pdr',
    category: 'Long Cannon',
    rank: 'V–IV',
    dmg: 15,
    penetration: 15,
    shots: 1,
    reloadTime: 13,
    range: 140,
    maxAngle: 16,
    scatter: 6,
    name: '8-pdr Culverin',
    desc: 'Long-range culverin with tight spread.',
  },
  {
    id: 'longcannon_culverin_16pdr',
    category: 'Long Cannon',
    rank: 'IV–III',
    dmg: 15,
    penetration: 15,
    shots: 1,
    reloadTime: 17.5,
    range: 140,
    maxAngle: 14,
    scatter: 6.5,
    name: '16-pdr Culverin',
    desc: 'Long-range medium culverin.',
  },
  {
    id: 'longcannon_18pdr',
    category: 'Long Cannon',
    rank: 'IV–III',
    dmg: 16,
    penetration: 16,
    shots: 1,
    reloadTime: 15,
    range: 145,
    maxAngle: 13,
    scatter: 8,
    name: '18-pdr Long Cannon',
    desc: 'Long-range medium cannon.',
  },
  {
    id: 'longcannon_scorcher_22pdr',
    category: 'Long Cannon',
    rank: 'III–II',
    dmg: 19,
    penetration: 19,
    shots: 1,
    reloadTime: 26,
    range: 148,
    maxAngle: 9,
    scatter: 9.5,
    name: '22-pdr Scorcher',
    desc: 'Long-range heavy culverin with high penetration.',
  },
  {
    id: 'longcannon_32pdr',
    category: 'Long Cannon',
    rank: 'I',
    dmg: 18.5,
    penetration: 18.5,
    shots: 1,
    reloadTime: 17.5,
    range: 150,
    maxAngle: 10,
    scatter: 10,
    name: '32-pdr Long Cannon',
    desc: 'Maximum range heavy long cannon.',
  },
  {
    id: 'longcannon_jericho_38pdr',
    category: 'Long Cannon',
    rank: 'I',
    dmg: 22,
    penetration: 22,
    shots: 1,
    reloadTime: 30.5,
    range: 153,
    maxAngle: 7,
    scatter: 12,
    name: '38-pdr Jericho',
    desc: 'Extreme-range heavy long cannon.',
  },

  // ─── Carronades ─────────────────────────────────────────────────────────────
  {
    id: 'carronade_12pdr',
    category: 'Carronade',
    rank: 'V–IV',
    dmg: 20,
    penetration: 20,
    shots: 1,
    reloadTime: 22,
    range: 105,
    maxAngle: 26,
    scatter: 9.5,
    name: '12-pdr Carronade',
    desc: 'Close-range carronade with high penetration.',
  },
  {
    id: 'carronade_16pdr',
    category: 'Carronade',
    rank: 'IV–III',
    dmg: 21.5,
    penetration: 21.5,
    shots: 1,
    reloadTime: 19.5,
    range: 110,
    maxAngle: 23,
    scatter: 11.5,
    name: '16-pdr Carronade',
    desc: 'Medium-tier carronade.',
  },
  {
    id: 'carronade_24pdr',
    category: 'Carronade',
    rank: 'II–I',
    dmg: 21.5,
    penetration: 21.5,
    shots: 1,
    reloadTime: 25.5,
    range: 110,
    maxAngle: 21,
    scatter: 12,
    name: '24-pdr Carronade',
    desc: 'Heavy carronade with devastating close-range power.',
  },
  {
    id: 'carronade_28pdr',
    category: 'Carronade',
    rank: 'III–II',
    dmg: 23,
    penetration: 23,
    shots: 1,
    reloadTime: 22.5,
    range: 115,
    maxAngle: 20,
    scatter: 14.5,
    name: '28-pdr Carronade',
    desc: 'Heavy medium carronade.',
  },
  {
    id: 'carronade_stormbringer_32pdr',
    category: 'Carronade',
    rank: 'II–I',
    dmg: 25.5,
    penetration: 25.5,
    shots: 1,
    reloadTime: 27.5,
    range: 105,
    maxAngle: 16,
    scatter: 13,
    name: '32-pdr Stormbringer',
    desc: 'Heavy carronade with devastating close-range output.',
  },
  {
    id: 'carronade_42pdr',
    category: 'Carronade',
    rank: 'I',
    dmg: 27,
    penetration: 27,
    shots: 1,
    reloadTime: 26,
    range: 120,
    maxAngle: 15,
    scatter: 18,
    name: '42-pdr Carronade',
    desc: 'Devastating close-range heavy carronade.',
  },
  {
    id: 'carronade_colossus_48pdr',
    category: 'Carronade',
    rank: 'I',
    dmg: 30,
    penetration: 30,
    shots: 1,
    reloadTime: 32,
    range: 110,
    maxAngle: 12,
    scatter: 16,
    name: '48-pdr Colossus',
    desc: 'Maximum calibre carronade.',
  },

  // ─── Bombards ───────────────────────────────────────────────────────────────
  {
    id: 'bombard_basilisk',
    category: 'Bombard',
    rank: 'V–IV',
    dmg: 17.5,
    penetration: 17.5,
    shots: 1,
    reloadTime: 18.5,
    range: 150,
    maxAngle: 25,
    scatter: 4,
    name: 'Basilisk',
    desc: 'Long-range accurate bombard.',
    bowSternOnly: true,
  },
  {
    id: 'bombard_twin_6pdr',
    category: 'Bombard',
    rank: 'V–IV',
    dmg: 16,
    penetration: 16,
    shots: 2,
    reloadTime: 20,
    range: 115,
    maxAngle: 12,
    scatter: 9,
    name: 'Twin 6-pdr',
    desc: 'Twin-barrel bombard firing two shots.',
    bowSternOnly: true,
  },
  {
    id: 'bombard_twin_14pdr',
    category: 'Bombard',
    rank: 'IV–III',
    dmg: 17,
    penetration: 17,
    shots: 2,
    reloadTime: 23.5,
    range: 120,
    maxAngle: 10,
    scatter: 11,
    name: 'Twin 14-pdr',
    desc: 'Twin-barrel bombard firing two shots.',
    bowSternOnly: true,
  },
  {
    id: 'bombard_triple_10pdr',
    category: 'Bombard',
    rank: 'IV–III',
    dmg: 14,
    penetration: 14,
    shots: 3,
    reloadTime: 28.5,
    range: 135,
    maxAngle: 8,
    scatter: 13,
    name: 'Triple 10-pdr',
    desc: 'Triple-barrel bombard firing three shots.',
    bowSternOnly: true,
  },
  {
    id: 'bombard_zeus',
    category: 'Bombard',
    rank: 'III–II',
    dmg: 19,
    penetration: 19,
    shots: 1,
    reloadTime: 21.5,
    range: 155,
    maxAngle: 21,
    scatter: 5,
    name: 'Zeus',
    desc: 'Long-range accurate bombard.',
    bowSternOnly: true,
  },
  {
    id: 'bombard_onager',
    category: 'Bombard',
    rank: 'III–II',
    dmg: 28,
    penetration: 28,
    shots: 1,
    reloadTime: 20.5,
    range: 85,
    maxAngle: 25,
    scatter: 13.5,
    name: 'Onager',
    desc: 'Powerful close-range bombard.',
    bowSternOnly: true,
  },
  {
    id: 'bombard_poseidon',
    category: 'Bombard',
    rank: 'III–II',
    dmg: 26,
    penetration: 26,
    shots: 1,
    reloadTime: 18,
    range: 80,
    maxAngle: 30,
    scatter: 11,
    name: 'Poseidon',
    desc: 'Powerful close-range bombard.',
    bowSternOnly: true,
  },
  {
    id: 'bombard_twin_20pdr',
    category: 'Bombard',
    rank: 'II–I',
    dmg: 20,
    penetration: 20,
    shots: 2,
    reloadTime: 27,
    range: 125,
    maxAngle: 8,
    scatter: 14,
    name: 'Twin 20-pdr',
    desc: 'Twin-barrel heavy bombard firing two shots.',
    bowSternOnly: true,
  },
  {
    id: 'bombard_triple_16pdr',
    category: 'Bombard',
    rank: 'II–I',
    dmg: 16.5,
    penetration: 16.5,
    shots: 3,
    reloadTime: 33,
    range: 140,
    maxAngle: 6,
    scatter: 16,
    name: 'Triple 16-pdr',
    desc: 'Triple-barrel heavy bombard firing three shots.',
    bowSternOnly: true,
  },
  {
    id: 'bombard_gilgamesh',
    category: 'Bombard',
    rank: 'I',
    dmg: 22,
    penetration: 22,
    shots: 1,
    reloadTime: 25,
    range: 160,
    maxAngle: 16,
    scatter: 6,
    name: 'Gilgamesh',
    desc: 'Elite long-range heavy bombard.',
    bowSternOnly: true,
  },
  {
    id: 'bombard_mjolnir',
    category: 'Bombard',
    rank: 'I',
    dmg: 32.5,
    penetration: 32.5,
    shots: 1,
    reloadTime: 24,
    range: 90,
    maxAngle: 20,
    scatter: 17,
    name: 'Mjolnir',
    desc: 'Maximum calibre heavy bombard.',
    bowSternOnly: true,
  },

  // ─── Mortars ────────────────────────────────────────────────────────────────
  {
    id: 'mortar_6in',
    category: 'Mortar',
    rank: 'VII–V',
    dmg: 100,
    penetration: 100,
    shots: 1,
    reloadTime: 20,
    range: 135,
    rangeMin: 60,
    maxAngle: 360,
    scatter: 11,
    name: '6-inch Mortar',
    desc: 'Range 60–135m. Splash radius 11. Reduction 2s. Damage to structures ×2.',
    splashRadius: 11,
    reduction: 2,
    structureBonus: true,
  },
  {
    id: 'mortar_7in',
    category: 'Mortar',
    rank: 'VI–IV',
    dmg: 125,
    penetration: 125,
    shots: 1,
    reloadTime: 24,
    range: 145,
    rangeMin: 75,
    maxAngle: 360,
    scatter: 11,
    name: '7-inch Mortar',
    desc: 'Range 75–145m. Splash radius 11. Reduction 3s. Damage to structures ×2.',
    splashRadius: 11,
    reduction: 3,
    structureBonus: true,
  },
  {
    id: 'mortar_8in',
    category: 'Mortar',
    rank: 'V–III',
    dmg: 150,
    penetration: 150,
    shots: 1,
    reloadTime: 31,
    range: 155,
    rangeMin: 85,
    maxAngle: 360,
    scatter: 12,
    name: '8-inch Mortar',
    desc: 'Range 85–155m. Splash radius 12. Reduction 4s. Damage to structures ×2.',
    splashRadius: 12,
    reduction: 4,
    structureBonus: true,
  },
  {
    id: 'mortar_9in',
    category: 'Mortar',
    rank: 'IV–II',
    dmg: 180,
    penetration: 180,
    shots: 1,
    reloadTime: 35,
    range: 150,
    rangeMin: 75,
    maxAngle: 360,
    scatter: 13,
    name: '9-inch Mortar',
    desc: 'Range 75–150m. Splash radius 13. Reduction 4s. Damage to structures ×2.',
    splashRadius: 13,
    reduction: 4,
    structureBonus: true,
  },
  {
    id: 'mortar_10in',
    category: 'Mortar',
    rank: 'III–I',
    dmg: 210,
    penetration: 210,
    shots: 1,
    reloadTime: 38,
    range: 145,
    rangeMin: 65,
    maxAngle: 360,
    scatter: 14,
    name: '10-inch Mortar',
    desc: 'Range 65–145m. Splash radius 14. Reduction 5s. Damage to structures ×2.',
    splashRadius: 14,
    reduction: 5,
    structureBonus: true,
  },
  {
    id: 'mortar_11in',
    category: 'Mortar',
    rank: 'II–I',
    dmg: 245,
    penetration: 245,
    shots: 1,
    reloadTime: 42,
    range: 140,
    rangeMin: 60,
    maxAngle: 360,
    scatter: 15,
    name: '11-inch Mortar',
    desc: 'Range 60–140m. Splash radius 15. Reduction 5.5s. Damage to structures ×2.',
    splashRadius: 15,
    reduction: 5.5,
    structureBonus: true,
  },
  {
    id: 'mortar_heavy',
    category: 'Mortar',
    rank: 'I',
    dmg: 155,
    penetration: 155,
    shots: 1,
    reloadTime: 34,
    range: 155,
    rangeMin: 95,
    maxAngle: 360,
    scatter: 9,
    name: 'Heavy Mortar',
    desc: 'Range 95–155m. Splash radius 9. Reduction 4s. Preparation 4.8s. Damage to structures ×2.',
    splashRadius: 9,
    reduction: 4,
    preparation: 4.8,
    structureBonus: true,
  },

  // ─── Special ────────────────────────────────────────────────────────────────
  {
    id: 'special_imperial_bombard',
    category: 'Special',
    rank: 'I',
    dmg: 34,
    penetration: 34,
    shots: 8,
    reloadTime: 22,
    range: 135,
    maxAngle: 6,
    scatter: 12,
    name: 'Imperial Bombard',
    desc: '8-barrel volley — 34 pen × 8 shots. For special ships only.',
    specialShipOnly: true,
  },
  {
    id: 'special_alchemical_fire',
    category: 'Special',
    rank: 'I',
    dmg: 80,
    penetration: 80,
    shots: 1,
    reloadTime: 468,
    range: 60,
    maxAngle: 6,
    scatter: 10,
    name: 'Alchemical Fire',
    desc: '80 dmg/sec continuous fire over 468s firing time. For special ships only.',
    specialShipOnly: true,
  },
  {
    id: 'special_barrel_launcher',
    category: 'Special',
    rank: 'I',
    dmg: 90,
    penetration: 90,
    shots: 1,
    reloadTime: 25,
    range: 140,
    rangeMin: 80,
    maxAngle: 360,
    scatter: 22,
    name: 'Barrel Launcher',
    desc: 'Range 80–140m. Splash radius 22. Reduction 4s. Preparation 3.5s. Damage to structures ×2.',
    splashRadius: 22,
    reduction: 4,
    preparation: 3.5,
    structureBonus: true,
  },
]

// ─── Helpers ─────────────────────────────────────────────────────────────────

export const CANNON_CATEGORIES = [
  'Cannon',
  'Long Cannon',
  'Carronade',
  'Bombard',
  'Mortar',
  'Special',
] as const

export function getCannonById(id: string): Cannon {
  return CANNONS.find((c) => c.id === id) ?? CANNONS[0]
}

export function getCannonsByCategory(category: string): Cannon[] {
  return CANNONS.filter((c) => c.category === category)
}
